services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pricewatcher_mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DockerMSSQL!2025"
    ports:
      - "1400:1433"
    volumes:
      - pricewatcher_mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DockerMSSQL!2025 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10

  pricewatcherapi:
    build:
      context: .
      dockerfile: PriceWatcher.Api/Dockerfile
    container_name: pricewatcherapi
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=PriceWatcherDb;User Id=sa;Password=YourPassword123!;Integrated Security=False;TrustServerCertificate=True;
    ports:
      - "7060:8080"  # HTTP
      - "7061:8081"  # HTTPS
    networks:
      - pricenet


  catalogloader:
    build:
      context: .
      dockerfile: CatalogLoader/Dockerfile
    container_name: catalogloader
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=PriceWatcherDb;User Id=sa;Password=YourPassword123!;Integrated Security=False;TrustServerCertificate=True;
    networks:
      - pricenet

volumes:
  pricewatcher_mssql_data:

networks:
  pricenet:
    driver: bridge