services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pricewatcher-sql
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  pricewatcherapi:
    build:
      context: .
      dockerfile: PriceWatcher.Api/Dockerfile
    container_name: pricewatcherapi
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=PriceWatcherDb;User Id=sa;Password=YourPassword123!;Integrated Security=False;TrustServerCertificate=True;
    ports:
      - "7060:8081"  # HTTP
    networks:
      - pricenet


  catalogloader:
    build:
      context: .
      dockerfile: CatalogLoader/Dockerfile
    container_name: catalogloader
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=PriceWatcherDb;User Id=sa;Password=YourPassword123!;Integrated Security=False;TrustServerCertificate=True;
    networks:
      - pricenet

volumes:
  sql_data:

networks:
  pricenet:
    driver: bridge